In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

In [ ]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"

# Assign colum names to the dataset
names = ['sepal-length', 'sepal-width', 'petal-length', 'petal-width', 'Target']

# Read dataset to pandas dataframe
dataset = pd.read_csv(url, names=names)

In [ ]:
dataset.head(5)

   sepal-length  sepal-width  petal-length  petal-width       Target
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
dataset['Target'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
dataset.shape

(150, 5)

In [ ]:
X = dataset.iloc[:, 0:4]
Y = dataset.loc[:, "Target"]

In [ ]:
X.head()

   sepal-length  sepal-width  petal-length  petal-width
0           5.1          3.5           1.4          0.2
1           4.9          3.0           1.4          0.2
2           4.7          3.2           1.3          0.2
3           4.6          3.1           1.5          0.2
4           5.0          3.6           1.4          0.2

In [ ]:
Y

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Target, Length: 150, dtype: object

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1, random_state = 77, )

In [ ]:
X_train.shape

(135, 4)

In [ ]:
linear_SVM = SVC(kernel = "poly", C = 10, gamma = 0.1) # model init
linear_SVM.fit(X_train, y_train) # model training

SVC(C=10, gamma=0.1, kernel='poly')

In [ ]:
train_predictions = linear_SVM.predict(X_train)
predictions = linear_SVM.predict(X_test)
predictions

array(['Iris-versicolor', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa'], dtype=object)

In [ ]:
print(confusion_matrix(y_test, predictions))
print(classification_report(y_test, predictions))

[[6 0 0]
 [0 3 0]
 [0 1 5]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00         6
Iris-versicolor       0.75      1.00      0.86         3
 Iris-virginica       1.00      0.83      0.91         6

       accuracy                           0.93        15
      macro avg       0.92      0.94      0.92        15
   weighted avg       0.95      0.93      0.94        15

In [ ]:
print(confusion_matrix(y_train, train_predictions))
print(classification_report(y_train, train_predictions))

[[44  0  0]
 [ 0 46  1]
 [ 0  0 44]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        44
Iris-versicolor       1.00      0.98      0.99        47
 Iris-virginica       0.98      1.00      0.99        44

       accuracy                           0.99       135
      macro avg       0.99      0.99      0.99       135
   weighted avg       0.99      0.99      0.99       135